version: "3.7"

services:
  database:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - type: volume
        source: database-volume
        target: /var/lib/mysql
  rabbit:
    image: rabbitmq:management
    ports:
      - 15672:15672
  service-discovery:
    image: cine/service-discovery
  api-gateway:
    image: cine/api-gateway
    ports:
      - 8080:8080
    environment:
      SERVICE_DISCOVERY_HOSTS: http://service-discovery:8761/eureka/
    depends_on:
      - service-discovery
  movies:
    image: cine/movies
    environment:
      DB_HOST: database
      RABBIT_HOST: rabbit
      SERVICE_DISCOVERY_HOSTS: http://service-discovery:8761/eureka/
    depends_on:
      - database
      - service-discovery
  sessions:
    image: cine/movie-sessions
    environment:
      DB_HOST: database
      RABBIT_HOST: rabbit
      SERVICE_DISCOVERY_HOSTS: http://service-discovery:8761/eureka/
    depends_on:
      - database
      - service-discovery
  theaters:
    image: cine/movie-theaters
    environment:
      DB_HOST: database
      RABBIT_HOST: rabbit
      SERVICE_DISCOVERY_HOSTS: http://service-discovery:8761/eureka/
    depends_on:
      - database
      - service-discovery

volumes:
  database-volume:
