version: "3.7"

services:
  database:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: database-volume
        target: /var/lib/mysql
  rabbit:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
#  movie:
#    image: cine/movie
#    ports:
#      - 8080:8080
#    environment:
#      DB_HOST: database
#  session:
#    image: cine/movie-sessions
#    ports:
#      - 8100:8080
#    environment:
#      DB_HOST: database
#  theaters:
#    image: cine/movie-theaters
#    ports:
#      - 8081:8080
#    environment:
#      DB_HOST: database

volumes:
  database-volume:
