version: "3.7"

services:
  database:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - type: volume
        source: database-volume
        target: /var/lib/mysql
    ports:
      - 3306:3306
  rabbit:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
  service-discovery:
    image: cine/service-discovery
    ports:
      - 8761:8761
    restart: on-failure
  api-gateway:
    image: cine/api-gateway
    ports:
      - 8080:8080
    environment:
      SERVICE_DISCOVERY_HOSTS: http://service-discovery:8761/eureka/
    depends_on:
      - movies
      - sessions
      - theaters
      - unavailable
    restart: on-failure
  movies:
    image: cine/movies
    environment:
      DB_HOST: database
      RABBIT_HOST: rabbit
      SERVICE_DISCOVERY_HOSTS: http://service-discovery:8761/eureka/
    depends_on:
      - database
      - service-discovery
    restart: on-failure
  sessions:
    image: cine/movie-sessions
    environment:
      DB_HOST: database
      RABBIT_HOST: rabbit
      SERVICE_DISCOVERY_HOSTS: http://service-discovery:8761/eureka/
    depends_on:
      - database
      - service-discovery
    restart: on-failure
  theaters:
    image: cine/movie-theaters
    environment:
      DB_HOST: database
      RABBIT_HOST: rabbit
      SERVICE_DISCOVERY_HOSTS: http://service-discovery:8761/eureka/
    depends_on:
      - database
      - service-discovery
    restart: on-failure
  unavailable:
    image: cine/unavailability
    environment:
      DB_HOST: database
      RABBIT_HOST: rabbit
      SERVICE_DISCOVERY_HOSTS: http://service-discovery:8761/eureka/
    depends_on:
      - database
      - service-discovery
    restart: on-failure

volumes:
  database-volume:
    name: cine
    external: true

