eureka:
  client:
    register-with-eureka: false
zuul:
  routes:
    movies:
      stripPrefix: false
      path: /movies/**
      serviceId: movies
    theater:
      stripPrefix: false
      path: /theater/**
      serviceId: theaters
    session:
      stripPrefix: false
      path: /sessions/**
      serviceId: sessions
    unavailability:
      path: /unavailability/**
      serviceId: unavailability