server:
  port: 0
spring:
  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sessions}?createDatabaseIfNotExist=true&&useSSL=false"
    username: "${DB_USERNAME:root}"
    password: "${DB_PASSWORD:}"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: sessions
  cloud:
    stream:
      bindings:
        create-movies:
          content-type: application/json
        create-movie-theaters:
          content-type: application/json
cine:
  movie:
    show-url: "http://MOVIES/movies/{id}"
  theater:
    show-url: "http://THEATERS/theater/{id}"
