server:
  port: 8100
spring:
  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sessions}?createDatabaseIfNotExist=true&&useSSL=false"
    username: "${DB_USERNAME:root}"
    password: "${DB_PASSWORD:}"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: sessions
cine:
  movie:
    show-url: "${MOVIE_BASE_URL:http://localhost:8080}/movies/{id}"
  theater:
    show-url: "${MOVIE_THEATER_BASE_URL:http://localhost:8090}/theater/{id}"