spring:
  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:movies}?createDatabaseIfNotExist=true&&useSSL=false"
    username: "${DB_USERNAME:root}"
    password: "${DB_PASSWORD:}"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: movies
  cloud:
    stream:
      bindings:
        create-movies:
          content-type: application/json
  rabbitmq:
    host: "${RABBIT_HOST:localhost}"
    port: "${RABBIT_PORT:5672}"
    username: "${RABBIT_USERNAME:guest}"
    password: "${RABBIT_PASSWORD:guest}"


server:
  port: 0

